---

- name: SeaWeedFS | Remove service swfs-filer | yum
  file:
    path: /etc/systemd/system/swfs-filer.service
    state: absent
  tags:
    - prune-all
  when: "'prune-all' in ansible_run_tags"

- name: SeaWeedFS | Setup service swfs-filer | yum
  template:
    src: system/swfs-filer.service.j2
    dest: "/etc/systemd/system/swfs-filer.service"
    mode: 0700

- name: SeaWeedFS | Create filer config file
  template: 
    src: filer.toml.j2
    dest: "{{weed_folder}}/filer.toml"